--made by hacsu8166

function[]
[L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1] end
gg.toast('bypassing.')
gg.toast('bypassing..')
gg.toast('bypassing...')
  if bypass[gg.toast]
  bypassedSUCCESSmsg---> gg.toast('BYPASSED')
  if bypass [gg.toast]
  bypassedFAILEDmsg ----> gg.toast('bypass failed.. maybe u did something wrong... or an bug.. retry?   join https://dsc.gg/filos-gg for report of bugs')
 function[]
[L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1]
 29587 79844 9785 5479852479825437 47 44 0723 2 7427 20 74 8742374283 4237  7478 9789789 778 59877895754 24295878 3 856325 86992 852983 9 296365494545 296436 94 265495 65 6 4263595 2839 2583 9258692 8592 859 5 629[L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1][L2]
 [12]
[23]
 [L1]
         get bypass
get failed
                    localData
               'criex bypASS is fake'
     12][43[124]1[42]2[[4]][4]4123[;3142'132'43121432'432'
/1324'/4/\324/[342]\[/432\[]432\[/43\[342\[]432\[432\[32342[\]4321\[21[4/3243\1[/12/1243[1[/423\24[/2/[24[/24\[12[32\[/321\[/123\[/43\[/324\[/123\[/3\[/32\[/2\[/2 \[1/\[21/1 [\ [3\ 2[1\/[3 [3\ [/3[2[/ 43\[312/ [4123\][4 1[\]243 [\]2134\[]/1\42[\[425[\243[]\][34\][145\][/34\][[45\[/2 4\/[24\[24 \[/42  4\;.]\ 4.3\. 243\2].4 3. 43\.4 2];;].4.42.]42 5\ .24.;23 4\;].3.42 3.];34;423.\4.2 ]2\3t]235.t2]5t.24]t2]5.t45].234].523]4.523]4.5]3.4523]4.532]4.545.7]6.8].70].780.]7]90.75.]3.44.523.54.24].

criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           

\345\43\34\53\4534\534\53\4534\534\534\534\53\453\4534\53\4\345\345\35\345\345\345\345\345\6\567\57\5\6765\7856\76578\6578]7685\6578\65\8756\7856\87\67\86\87\68\76\8768989\090-\980-\890\-890\-98\0-8\90-\98\\4\23\421\34\2\4\\\234\23\42134\\\2134214\\\234\324\1324\3241\1243\124334\534\523\45324\523\452345\34\5345\345\345\345\345\345\534\534\534\5324\5342\5324\5342\534\53\453\45\3245\4\\4\4\34\4\43\\\3\34\34\43\4\4\4\\4\4\4\4\4\4\4\4\\4 end
criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           criex
   bypASS
      fake
        m
             ,
                       m                                                                         m                                   m                                                                                           b                          g                                     b                 y               p       a              s                           v                    er y                     re                      a                 l           end
      end
                  end
      end
